export const DEFAULT_ENGINE = 'dot';
export const DEFAULT_FORMAT = 'svg';

export const KNOWN_ENGINES = [
  'dot',
  'neato',
  'fdp',
  'sfdp',
  'circo',
  'twopi',
  'osage',
  'patchwork',
] as const;

export const KNOWN_TEXT_FORMATS = [
  'svg',
  'json',
  'dot',
  'xdot',
  'plain',
] as const;

export type GraphvizEngine = (typeof KNOWN_ENGINES)[number] | (string & {});
export type GraphvizFormat = (typeof KNOWN_TEXT_FORMATS)[number] | (string & {});
export type GraphvizErrorLevel = 'error' | 'warning';
export type GraphvizAttributeValue = string | number | boolean | { html: string };

export interface GraphvizImageSize {
  name: string;
  width: string | number;
  height: string | number;
}

export interface GraphvizRenderOptions {
  engine?: GraphvizEngine;
  format?: GraphvizFormat;
  yInvert?: boolean;
  reduce?: boolean;
  graphAttributes?: Record<string, GraphvizAttributeValue>;
  nodeAttributes?: Record<string, GraphvizAttributeValue>;
  edgeAttributes?: Record<string, GraphvizAttributeValue>;
  images?: GraphvizImageSize[];
}

export interface GraphvizRenderIssue {
  level?: GraphvizErrorLevel;
  message: string;
}

export interface GraphvizCapabilities {
  graphvizVersion: string;
  engines: string[];
  formats: string[];
}

export interface GraphvizRenderDiagnostics {
  output: string;
  issues: GraphvizRenderIssue[];
  capabilities: GraphvizCapabilities;
}

export interface GraphvizBatchDiagnostics {
  output: Record<string, string>;
  issues: GraphvizRenderIssue[];
  capabilities: GraphvizCapabilities;
}

export type GraphvizWebErrorCode =
  | 'UNSUPPORTED_ENGINE'
  | 'UNSUPPORTED_FORMAT'
  | 'RENDER_FAILED'
  | 'WORKER_UNAVAILABLE'
  | 'TIMEOUT'
  | 'DISPOSED';

export class GraphvizWebError extends Error {
  readonly code: GraphvizWebErrorCode;
  readonly issues: GraphvizRenderIssue[];

  constructor(
    code: GraphvizWebErrorCode,
    message: string,
    options: { issues?: GraphvizRenderIssue[]; cause?: unknown } = {}
  ) {
    super(message);
    this.name = 'GraphvizWebError';
    this.code = code;
    this.issues = options.issues ?? [];

    if (options.cause !== undefined) {
      (this as Error & { cause?: unknown }).cause = options.cause;
    }
  }
}

export interface VizSingleRenderResult {
  status: 'success' | 'failure';
  output?: string;
  errors: GraphvizRenderIssue[];
}

export interface VizBatchRenderResult {
  status: 'success' | 'failure';
  output?: Record<string, string>;
  errors: GraphvizRenderIssue[];
}

export interface VizWasmInstance {
  readonly graphvizVersion: string;
  readonly engines: string[];
  readonly formats: string[];
  render(input: string, options?: GraphvizRenderOptions): VizSingleRenderResult;
  renderFormats(
    input: string,
    formats: string[],
    options?: GraphvizRenderOptions
  ): VizBatchRenderResult;
}

export interface VizWasmModule {
  instance(): Promise<VizWasmInstance>;
}

export type LoadVizWasmModule = () => Promise<VizWasmModule>;

export interface GraphvizWorkerRequest {
  id: number;
  action:
    | 'preload'
    | 'capabilities'
    | 'render'
    | 'renderDetailed'
    | 'renderMany'
    | 'renderManyDetailed'
    | 'dispose';
  dot?: string;
  formats?: string[];
  options?: GraphvizRenderOptions;
}

export interface GraphvizWorkerErrorPayload {
  code: GraphvizWebErrorCode;
  message: string;
  issues?: GraphvizRenderIssue[];
}

export type GraphvizWorkerResponse =
  | {
      id: number;
      ok: true;
      value: unknown;
    }
  | {
      id: number;
      ok: false;
      error: GraphvizWorkerErrorPayload;
    };

export async function loadDefaultVizWasmModule(): Promise<VizWasmModule> {
  // Import the compiled Wasm module from output/wasm/viz.js
  // This module is generated by emscripten with MODULARIZE=1
  let vizModuleFactory;
  try {
    vizModuleFactory = await import('output/wasm/viz.js');
  } catch (error) {
    // In test environment or when wasm is not available,
    // provide a helpful error message
    throw new Error(
      'Wasm module not found. Make sure to build the Wasm module first: npm run build:wasm'
    );
  }

  const VizModuleFactory = vizModuleFactory.default;

  // Create a wrapper that conforms to the VizWasmModule interface
  // The factory returns a Promise that resolves to the Emscripten instance
  return {
    instance: async () => {
      const emscriptenInstance = await VizModuleFactory();
      return wrapEmscriptenInstance(emscriptenInstance);
    },
  };
}

// Wrapper function to adapt Emscripten instance to VizWasmInstance interface
function wrapEmscriptenInstance(emInstance: any): VizWasmInstance {
  return {
    get graphvizVersion(): string {
      const getVersion = emInstance.cwrap('gv_version', 'string', []);
      return getVersion();
    },

    get engines(): string[] {
      const getEngines = emInstance.cwrap('gv_get_engines', 'string', []);
      return JSON.parse(getEngines());
    },

    get formats(): string[] {
      const getFormats = emInstance.cwrap('gv_get_formats', 'string', []);
      return JSON.parse(getFormats());
    },

    render(input: string, options?: GraphvizRenderOptions): VizSingleRenderResult {
      const render = emInstance.cwrap(
        'gv_render',
        'string',
        ['string', 'string']
      );
      try {
        const optionsJson = JSON.stringify(options || {});
        const resultJson = render(input, optionsJson);
        return JSON.parse(resultJson);
      } catch (error) {
        return {
          status: 'failure',
          errors: [
            {
              level: 'error',
              message: error instanceof Error ? error.message : String(error),
            },
          ],
        };
      }
    },

    renderFormats(
      input: string,
      formats: string[],
      options?: GraphvizRenderOptions
    ): VizBatchRenderResult {
      const renderFormats = emInstance.cwrap(
        'gv_render_formats',
        'string',
        ['string', 'string', 'string']
      );
      try {
        const formatsJson = JSON.stringify(formats);
        const optionsJson = JSON.stringify(options || {});
        const resultJson = renderFormats(input, formatsJson, optionsJson);
        return JSON.parse(resultJson);
      } catch (error) {
        return {
          status: 'failure',
          errors: [
            {
              level: 'error',
              message: error instanceof Error ? error.message : String(error),
            },
          ],
        };
      }
    },
  };
}

export function normalizeRenderOptions(
  options: GraphvizRenderOptions = {}
): GraphvizRenderOptions {
  return {
    ...options,
    engine: options.engine ?? DEFAULT_ENGINE,
    format: options.format ?? DEFAULT_FORMAT,
  };
}

export function snapshotCapabilities(viz: VizWasmInstance): GraphvizCapabilities {
  return {
    graphvizVersion: viz.graphvizVersion,
    engines: [...viz.engines],
    formats: [...viz.formats],
  };
}

export function issuesToMessage(
  issues: GraphvizRenderIssue[],
  fallback: string
): string {
  const messages = issues
    .map((issue) => issue.message.trim())
    .filter((message) => message.length > 0);

  return messages.length > 0 ? messages.join('; ') : fallback;
}

export function assertEngineSupported(
  viz: VizWasmInstance,
  engine: string | undefined
): void {
  if (engine && !viz.engines.includes(engine)) {
    throw new GraphvizWebError(
      'UNSUPPORTED_ENGINE',
      `Engine "${engine}" is not available in this Wasm build. Supported engines: ${viz.engines.join(', ')}.`
    );
  }
}

export function assertFormatSupported(
  viz: VizWasmInstance,
  format: string | undefined
): void {
  if (format && !viz.formats.includes(format)) {
    throw new GraphvizWebError(
      'UNSUPPORTED_FORMAT',
      `Format "${format}" is not available in this Wasm build. Supported formats: ${viz.formats.join(', ')}.`
    );
  }
}

export function assertFormatsSupported(
  viz: VizWasmInstance,
  formats: string[]
): void {
  const unsupported = formats.filter((format) => !viz.formats.includes(format));

  if (unsupported.length > 0) {
    throw new GraphvizWebError(
      'UNSUPPORTED_FORMAT',
      `Formats "${unsupported.join(', ')}" are not available in this Wasm build. Supported formats: ${viz.formats.join(', ')}.`
    );
  }
}

export function assertActive(disposed: boolean, surface: string): void {
  if (disposed) {
    throw new GraphvizWebError('DISPOSED', `${surface} has already been disposed.`);
  }
}
